scrape_configs:
  - job_name: 'coinApp'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra-exporter:8080']