spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: exchange-service
#          uri: lb://exchange-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**, /api/csrf/**
